<?xml version="1.0" encoding="utf-8" ?>
<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
    <Target Name="ILRepacker" AfterTargets="Build" Condition="$(Configuration.Contains('Release'))">
        <ItemGroup>
            <InputAssemblies Include="$(OutputPath)\$(AssemblyName).exe" />
            <InputAssemblies Include="@(ReferencePathWithRefAssemblies)" Condition="'%(filename)' == 'Newtonsoft.Json'" />
            <InputAssemblies Include="$(OutputPath)\System.Buffers.dll" />
            <InputAssemblies Include="$(OutputPath)\System.Memory.dll" />
            <InputAssemblies Include="$(OutputPath)\System.Numerics.Vectors.dll" />
            <InputAssemblies Include="$(OutputPath)\System.Runtime.CompilerServices.Unsafe.dll" />
        </ItemGroup>

        <ILRepack
                AllowDuplicateResources="false"
                DebugInfo="true"
                Parallel="true"
                Internalize="true"
                InputAssemblies="@(InputAssemblies)"
                TargetKind="WinExe"
                OutputFile="$(OutputPath)\$(AssemblyName).exe"
        />
    </Target>
    <Target Name="DeleteDlls" AfterTargets="ILRepacker" Condition="$(Configuration.Contains('Release'))">
        <ItemGroup>
            <FilesToDelete Include="$(OutputPath)\System.Buffers.dll"/>
            <FilesToDelete Include="$(OutputPath)\System.Memory.dll"/>
            <FilesToDelete Include="$(OutputPath)\System.Numerics.Vectors.dll"/>
            <FilesToDelete Include="$(OutputPath)\System.Runtime.CompilerServices.Unsafe.dll"/>
        </ItemGroup>
        
        <Delete Files="@(FilesToDelete)" />
    </Target>
</Project>
